# Hyperparameter sweep with nevergrad

data:
  data_root: dataset/clips
  annot_root: dataset/vq_splits
  video_bbox_root: dataset/bboxes
  split: val
  fps: 5.0
  subsample: False
  num_processes: 12
  num_processes_per_gpu: 2
  batch_size: 12
  debug_mode: False
  debug_count: 5
  rcnn_batch_size: 8

retrieval:
  rotate_crop: True

signals:
  smoothing_sigma: 5
  distance: 25
  width: 3
  prominence: 0.2
  wlen: 50
  peak_similarity_thresh: 0.0

logging:
  visualize: False
  save_dir: "visualizations"
  stats_save_path: "outputs.json.gz"

model:
  config_path: "config.yaml"
  checkpoint_path: "model.pth"
  score_thresh: 0.0
  subsampling_factor: 1.0
  recency_factor: 1.0
  cache_root: ""
  reference_pad: 16
  reference_size: 256

tracker:
  type: "kys" # Options: [ kys | pfilter ]
  pfilter:
    n_particles: 150
    resample_proportion: 1.0
    sim_thresh: 0.85
    use_deep_similarity: True
    debug: False
  kys_tracker:
    debug: False
    lost_thresh: 0.05
    model_path: "pretrained_models/kys.pth"
